sudo: required
services:
  - docker
before_install:
  - docker build -t jasnross/fibonacci-docker-client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run --rm jasnross/fibonacci-docker-client-test yarn run test --coverage
after_success:
  - docker build -t jasnross/fibonacci-docker-client ./client
  - docker build -t jasnross/fibonacci-docker-nginx ./nginx
  - docker build -t jasnross/fibonacci-docker-server ./server
  - docker build -t jasnross/fibonacci-docker-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push jasnross/fibonacci-docker-client
  - docker push jasnross/fibonacci-docker-nginx
  - docker push jasnross/fibonacci-docker-server
  - docker push jasnross/fibonacci-docker-worker
