version: "3.1"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=notapassword
  redis:
    image: redis:latest
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=notapassword
      - PGPORT=5432
    volumes:
      - ./server:/app
      - /app/node_modules
